### ISSUE TITLE
Grafi in kromatična števila (ne barve)

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/matematicne-aktivnosti#1]
PDF za "Grafi in kromatična števila" ima v naslovu še vedno besedo "barva" namesto "število". V besedilu je potem pravilno napisano.

**Comment by urhprimozic** [comment]
PDF in thumbnail sta popravljena.

**Comment by andrejbauer** [comment]
Ko zapreš issue, zraven v komentar napišeš, kateri commit ga je zaprl (še bolje: v commit message napišeš "close #1" in se bo vse zgodilo samo).
