### ISSUE TITLE
Prevod knjižice o ortoprojekcijah

### ISSUE THREAD

**Issue by MartinRadman** [ul-fmf/matematicne-aktivnosti#4]
Prevede naj se  [knjižico o ortoprojekcijah](http://jdh.hamkins.org/wp-content/uploads/2018/05/Fun-with-orthoprojection.pdf)
(Petrisa, Martin, Urh)

**Comment by andrejbauer** [comment]
Uhm, ko odpreš issue, ponavadi poveš, kaj se dogaja. Kaj naj bi to bilo?

**Comment by MartinRadman** [comment]
Urh je priporočal, da odprem issue glede prevajanja naslednje datoteke (ortoptojekcije). Ne vem točno še kaj so teli issue-ji, tako da možno da je nepotrebno.

**Comment by urhprimozic** [comment]
_Sem malo popravil issue. Sam se lažje spravim k delu, če je nekje ena barvasta stvar, ki jo na koncu lahko zaprem._

Kako naj sploh prevajamo **ortoprojekcije** ?

**Comment by MartinRadman** [comment]
Meni se zdi dosti standarden prevod. Mogoče je težava samo pri izrazu "unit block". "Enotski kvader" mogoče?

**Comment by andrejbauer** [comment]
@urhprimozic zdi se da iščeš "Milestones". En ali veš issues lahko združiš v "Milestone" (desni stolpec) in potem se vidi napredek. Recimo, za ortoprojekcije narediš issues: prevod, oblikovanje, scan, PDF in jih daš v Milestone "Ortoprojekcije".
