### ISSUE TITLE
Stran je grda na mobilnih napravah - responsive design

### ISSUE THREAD

**Issue by urhprimozic** [ul-fmf/matematicne-aktivnosti#5]
Na mobilnih napravah se stran ne prilagodi ekranu, besedilo pa uide izven ekrana.
Kakor vem, je na prejšnji temi vse delalo ok.

**Comment by andrejbauer** [comment]
Aha, bom pogledal. V bistvu sem vzel prejšnjo temo in več ali manj samo pobrisal ven desni stolpec.
