### ISSUE TITLE
Prevod

### ISSUE THREAD

**Issue by urhprimozic** [ul-fmf/matematicne-aktivnosti#6]
Prevede naj se [knjižico o ortoprojekcijah](http://jdh.hamkins.org/wp-content/uploads/2018/05/Fun-with-orthoprojection.pdf)
Prevedeva lahko skupaj z @MartinRadman , pa @petrisa-canji potem uredi pdf.

Verjetno nam uspe do naslednjega tedna?

**Comment by MartinRadman** [comment]
A gremo kar do četrtka narediti? Prejšnjič smo v dveh dneh uspeli.

**Comment by MartinRadman** [comment]
Narejeno
