### ISSUE TITLE
Oblikovanje PDFja

### ISSUE THREAD

**Issue by urhprimozic** [ul-fmf/matematicne-aktivnosti#7]
Uredi naj se slovenski pdf [o ortoprojekcijah](http://jdh.hamkins.org/wp-content/uploads/2018/05/Fun-with-orthoprojection.pdf)

**Comment by MartinRadman** [comment]
Narejeno

**Comment by andrejbauer** [comment]
Prosim lepo, ko imate issue in ga opravite in zaprete, je treba zraven napisati, v katerem commitu se je to opravilo. Torej, namesto "Narejeno." se napiše "Najrejeno v d45e83f", kjer sem uporabil magičnih hash, ki je zraven v commitu.

In še bolje je, če v message od commit napišeš "close #7", ker se bo potem issue sam zaprl in še referenca na commit se bo naredila.

Brez tega je grozno, ker se nikoli ne ve, kje je bilo kaj narejeno.
